apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: ek-test
  namespace: elastic-system
spec:
  version: 8.2.2
  count: 1
  elasticsearchRef:
    name: ek-test
  http:
    tls:
      selfSignedCertificate:
        disabled: true