apiVersion: v1
kind: Secret
metadata:
    name: mariadb-secret
    namespace: <namespace>
type: Opaque
data:
  mariadb-root-password: <password>
  mariadb-galera-mariabackup-password: <password>
  mariadb-password: <password>