apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rook-ceph-deshboard
  namespace: rook-ceph
  annotations:
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/server-snippet: |
      proxy_ssl_verify off;
spec:
  ingressClassName: ig1
  rules:
  - host: ceph.vattenlab.com
    http:
      paths:
      - backend:
          service:
            name: rook-ceph-mgr-dashboard
            port:
              name: https-dashboard
        path: /
        pathType: Prefix
  tls:
    - hosts:
        - ceph.vattenlab.com
      secretName: ceph.vattenlab.com