apiVersion: v1
kind: Namespace
metadata:
  name: host-path-storage

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: host-path-provisioner-service-account
  namespace: host-path-storage

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: host-path-provisioner-role
rules:
  - apiGroups: [ "" ]
    resources: [ "nodes", "persistentvolumeclaims", "configmaps" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "endpoints", "persistentvolumes", "pods" ]
    verbs: [ "*" ]
  - apiGroups: [ "" ]
    resources: [ "events" ]
    verbs: [ "create", "patch" ]
  - apiGroups: [ "storage.k8s.io" ]
    resources: [ "storageclasses" ]
    verbs: [ "get", "list", "watch" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: host-path-provisioner-bind
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: host-path-provisioner-role
subjects:
  - kind: ServiceAccount
    name: host-path-provisioner-service-account
    namespace: host-path-storage

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: host-path-provisioner
  namespace: host-path-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: host-path-provisioner
  template:
    metadata:
      labels:
        app: host-path-provisioner
    spec:
      serviceAccountName: host-path-provisioner-service-account
      containers:
        - name: host-path-provisioner
          image: quay.io/kubevirt/hostpath-provisioner:<image-version>
          imagePullPolicy: IfNotPresent
          command:
            - host-path-provisioner
            - --debug
            - start
            - --config
            - /etc/config/config.json
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config/
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      volumes:
        - name: config-volume
          configMap:
            name: host-path-config

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: host-path
provisioner: rancher.io/host-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: host-path-config
  namespace: host-path-storage
data:
  config.json: |-
    {
            "nodePathMap":[
            {
                    "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
                    "paths":["/opt/host-path-provisioner"]
            }
            ]
    }
  setup: |-
    #!/bin/sh
    set -eu
    mkdir -m 0777 -p "$VOL_DIR"
  teardown: |-
    #!/bin/sh
    set -eu
    rm -rf "$VOL_DIR"
  helperPod.yaml: |-
    apiVersion: v1
    kind: Pod
    metadata:
      name: helper-pod
    spec:
      containers:
      - name: helper-pod
        image: busybox
        imagePullPolicy: IfNotPresent

