apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tenant
  namespace: landlord
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tenant
  serviceName: tenant
  template:
    metadata:
      labels:
        app: tenant
    spec:
      containers:
      - env:
        - name: NS
          value: landlord
        - name: LOG_SERVER
          value: logger
        - name: KUSER_SERVER
          value: kuser
        - name: EXCLUDE
          value: .kube\|.bash_history
        image: quay.io/bookman117/landlord.tenant:1.0.0
        imagePullPolicy: Always
        name: tenant
        securityContext:
          capabilities:
            add:
            - AUDIT_WRITE
            - SYS_CHROOT
            - CAP_NET_RAW
        volumeMounts:
        - mountPath: /home/workdir
          name: workdir
      restartPolicy: Always
      initContainers:
        - name: init-container
          image: alpine
          command: ["/bin/sh"]
          args: ["-c", "chmod 777 /home/workdir"]
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: "/home/workdir"
              name: workdir
  volumeClaimTemplates:
  - metadata:
      name: workdir
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: <storageclass>