apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
  labels:
    app: metallb
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-pool-1
  namespace: metallb-system
spec:
  addresses:
  - <NETID>.<START>-<NETID>.<END>