apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: mlb1
      protocol: layer2
      #auto-assign: false
      addresses:
      - NETID.START-NETID.END